In [2]:
import numpy as np # importing numpy library for numerical operations
np.set_printoptions(precision =2, suppress = True) # setting print options to 2 decimal places and suppress scientific notation

In [3]:
a = np.array([1, 2, 3, 4, 5, 6]) # Creating a numpy array
print(a) # Printing the array

[1 2 3 4 5 6]


In [4]:
b = np.array([[10, 20, 30], [40, 50, 60]]) # Creating a 2D numpy array (matrix)
print(b) # Printing the matrix

[[10 20 30]
 [40 50 60]]


In [5]:
np.random.seed(25) # Setting seed for reproducibility
c = 36 * np.random.randn(6) # Generating 6 random numbers from a normal distribution
print(c) # Printing the random numbers

[  8.22  36.97 -30.23 -21.28 -34.45  -8.  ]


In [7]:
d = np.arange(1, 35) # Creating an array with values from 1 to 34
print(d) # Printing the array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34]


In [ ]:
print(a * 10) # multiplying each element of array 'a' by 10

[10 20 30 40 50 60]


In [10]:
print(c + a) # Adding array 'a' to array 'c' element-wise
print (c - a) # Subtracting array 'a' from array 'c' element-wise
print(c / a) # Dividing array 'c' by array 'a' element-wise
print(c * a) # Multiplying array 'c' by array 'a' element-wise

[  9.22  38.97 -27.23 -17.28 -29.45  -2.  ]
[  7.22  34.97 -33.23 -25.28 -39.45 -14.  ]
[  8.22  18.48 -10.08  -5.32  -6.89  -1.33]
[   8.22   73.94  -90.68  -85.13 -172.24  -48.02]
